<template>
    <div class="row">
        <div style="text-align: center">
            <b-form-select
                style="margin-left: 30px"
                name="sido"
                id="sido"
                v-model="sido"
                text-field="value"
                :options="sidooptions"
            ></b-form-select>
            <b-form-select
                style="margin-left: 30px"
                name="gugun"
                id="gugun"
                text-field="value"
                v-model="gugun"
                :options="gugunoption"
            ></b-form-select>
            <b-form-select
                style="margin-left: 30px"
                name="dong"
                id="dong"
                v-model="dong"
                text-field="value"
                :options="selectDong(gugun)"
            ></b-form-select>
            <b-button style="margin-left: 30px">상세 정보 검색</b-button>
        </div>
        <div id="map" class="map"></div>
    </div>
</template>

<script>
export default {
    mounted() {
        window.kakao && window.kakao.maps
            ? this.initMap()
            : this.addKakaoMapScript();
    },
    data() {
        return {
            sido: "서울특별시",
            gugun: null,
            dong: null,
            map: null,
            sidooptions: [{ value: "서울특별시" }],
            gugunoption: [
                { value: "종로구" },
                { value: "중구" },
                { value: "용산구" },
                { value: "성동구" },
                { value: "광진구" },
                { value: "동대문구" },
                { value: "중랑구" },
                { value: "성북구" },
                { value: "강북구" },
                { value: "은평구" },
                { value: "서대문구" },
                { value: "마포구" },
                { value: "양천구" },
                { value: "강서구" },
                { value: "구로구" },
                { value: "금천구" },
                { value: "영등포구" },
                { value: "동작구" },
                { value: "관악구" },
                { value: "서초구" },
                { value: "강남구" },
                { value: "송파구" },
                { value: "강동구" },
            ],

            dong0: [
                { value: "종로3가" },
                { value: "송현동" },
                { value: "내자동" },
                { value: "신교동" },
                { value: "서린동" },
                { value: "돈의동" },
                { value: "중학동" },
                { value: "적선동" },
                { value: "종로1가" },
                { value: "도렴동" },
                { value: "소격동" },
                { value: "사간동" },
                { value: "수송동" },
                { value: "효자동" },
                { value: "묘동" },
                { value: "신문로2가" },
                { value: "동숭동" },
                { value: "관훈동" },
                { value: "견지동" },
                { value: "안국동" },
                { value: "가회동" },
                { value: "청진동" },
                { value: "화동" },
                { value: "명륜2가" },
                { value: "통의동" },
                { value: "인의동" },
                { value: "명륜1가" },
                { value: "익선동" },
                { value: "계동" },
                { value: "장사동" },
                { value: "예지동" },
                { value: "와룡동" },
                { value: "봉익동" },
                { value: "통인동" },
                { value: "창성동" },
                { value: "공평동" },
                { value: "종로2가" },
                { value: "신문로1가" },
                { value: "관수동" },
                { value: "명륜3가" },
                { value: "청운동" },
                { value: "종로4가" },
                { value: "교남동" },
                { value: "관철동" },
                { value: "인사동" },
                { value: "낙원동" },
                { value: "삼청동" },
                { value: "창신동" },
                { value: "숭인동" },
                { value: "팔판동" },
                { value: "원서동" },
                { value: "궁정동" },
                { value: "구기동" },
                { value: "평창동" },
                { value: "당주동" },
                { value: "운니동" },
                { value: "사직동" },
                { value: "혜화동" },
                { value: "훈정동" },
                { value: "권농동" },
                { value: "경운동" },
                { value: "송월동" },
                { value: "내수동" },
                { value: "명륜4가" },
                { value: "원남동" },
                { value: "효제동" },
                { value: "이화동" },
                { value: "충신동" },
                { value: "세종로" },
                { value: "교북동" },
                { value: "필운동" },
                { value: "부암동" },
                { value: "연지동" },
                { value: "종로5가" },
                { value: "종로6가" },
                { value: "재동" },
                { value: "행촌동" },
                { value: "홍지동" },
                { value: "누하동" },
                { value: "신영동" },
                { value: "연건동" },
                { value: "평동" },
                { value: "홍파동" },
                { value: "무악동" },
                { value: "옥인동" },
                { value: "체부동" },
                { value: "누상동" },
            ],
            dong1: [
                "수하동",
                "다동",
                "수표동",
                "무학동",
                "남대문로1가",
                "남산동3가",
                "신당동",
                "회현동3가",
                "장교동",
                "장충동2가",
                "주자동",
                "무교동",
                "을지로1가",
                "남대문로2가",
                "남대문로4가",
                "태평로1가",
                "삼각동",
                "남대문로3가",
                "북창동",
                "회현동2가",
                "산림동",
                "충무로4가",
                "저동1가",
                "을지로2가",
                "봉래동2가",
                "충무로5가",
                "초동",
                "묵정동",
                "을지로7가",
                "입정동",
                "의주로2가",
                "만리동1가",
                "을지로4가",
                "정동",
                "충정로1가",
                "봉래동1가",
                "소공동",
                "필동2가",
                "필동3가",
                "예장동",
                "충무로2가",
                "명동1가",
                "충무로1가",
                "남대문로5가",
                "회현동1가",
                "저동2가",
                "예관동",
                "태평로2가",
                "남산동1가",
                "남창동",
                "명동2가",
                "인현동2가",
                "남산동2가",
                "남학동",
                "주교동",
                "충무로3가",
                "중림동",
                "의주로1가",
                "필동1가",
                "순화동",
                "흥인동",
                "만리동2가",
                "장충동1가",
                "광희동1가",
                "광희동2가",
                "쌍림동",
                "을지로6가",
                "을지로5가",
                "방산동",
                "오장동",
                "황학동",
                "인현동1가",
                "을지로3가",
                "서소문동",
            ],
            dong2: [""],
            dong3: [
                "하왕십리동",
                "응봉동",
                "송정동",
                "행당동",
                "금호동1가",
                "성수동2가",
                "상왕십리동",
                "성수동1가",
                "마장동",
                "옥수동",
                "용답동",
                "금호동2가",
                "금호동4가",
                "금호동3가",
                "홍익동",
                "도선동",
                "사근동",
            ],
            dong4: [
                "군자동",
                "구의동",
                "자양동",
                "중곡동",
                "능동",
                "광장동",
                "화양동",
            ],
            dong5: [
                "청량리동",
                "이문동",
                "전농동",
                "휘경동",
                "용두동",
                "장안동",
                "답십리동",
                "회기동",
                "제기동",
                "신설동",
            ],
            dong6: ["신내동", "중화동", "묵동", "망우동", "면목동", "상봉동"],
            dong7: [
                "돈암동",
                "동선동2가",
                "보문동2가",
                "정릉동",
                "보문동4가",
                "보문동5가",
                "보문동7가",
                "보문동1가",
                "장위동",
                "성북동1가",
                "동선동3가",
                "안암동3가",
                "석관동",
                "성북동",
                "동선동5가",
                "안암동1가",
                "동소문동3가",
                "삼선동5가",
                "동소문동5가",
                "삼선동3가",
                "동소문동2가",
                "보문동6가",
                "보문동3가",
                "안암동4가",
                "동소문동4가",
                "삼선동4가",
                "동선동4가",
                "삼선동2가",
                "길음동",
                "동소문동1가",
                "안암동2가",
                "삼선동1가",
                "종암동",
                "동선동1가",
                "동소문동7가",
                "하월곡동",
                "상월곡동",
                "안암동5가",
                "동소문동6가",
            ],
            dong8: ["미아동", "우이동", "번동", "수유동"],
            dong9: [
                "응암동",
                "신사동",
                "대조동",
                "수색동",
                "갈현동",
                "녹번동",
                "불광동",
                "증산동",
                "구산동",
                "역촌동",
                "진관동",
            ],
            dong10: [
                "충정로3가",
                "대현동",
                "영천동",
                "냉천동",
                "미근동",
                "북아현동",
                "홍제동",
                "현저동",
                "천연동",
                "충정로2가",
                "합동",
                "북가좌동",
                "홍은동",
                "남가좌동",
                "봉원동",
                "옥천동",
                "대신동",
                "신촌동",
                "연희동",
                "창천동",
            ],
            dong11: [
                "마포동",
                "용강동",
                "현석동",
                "토정동",
                "당인동",
                "하중동",
                "성산동",
                "구수동",
                "신정동",
                "망원동",
                "신공덕동",
                "도화동",
                "염리동",
                "서교동",
                "창전동",
                "노고산동",
                "아현동",
                "공덕동",
                "신수동",
                "중동",
                "연남동",
                "동교동",
                "합정동",
                "상수동",
                "상암동",
                "대흥동",
            ],
            dong12: ["신정동", "목동", "신월동"],
            dong13: [
                "오곡동",
                "공항동",
                "방화동",
                "개화동",
                "마곡동",
                "가양동",
                "과해동",
                "등촌동",
                "외발산동",
                "내발산동",
                "염창동",
                "화곡동",
                "오쇠동",
            ],
            dong14: [
                "구로동",
                "고척동",
                "오류동",
                "항동",
                "신도림동",
                "가리봉동",
                "개봉동",
                "천왕동",
                "궁동",
                "온수동",
            ],
            dong15: ["시흥동", "가산동", "독산동"],
            dong16: [
                "문래동4가",
                "당산동3가",
                "당산동",
                "신길동",
                "양화동",
                "양평동3가",
                "양평동",
                "영등포동5가",
                "당산동2가",
                "양평동6가",
                "당산동6가",
                "양평동1가",
                "문래동5가",
                "영등포동",
                "영등포동8가",
                "문래동2가",
                "문래동6가",
                "영등포동3가",
                "도림동",
                "대림동",
                "영등포동1가",
                "양평동5가",
                "문래동1가",
                "당산동5가",
                "영등포동6가",
                "영등포동7가",
                "영등포동4가",
                "양평동2가",
                "영등포동2가",
                "당산동1가",
                "문래동3가",
                "양평동4가",
                "당산동4가",
                "여의도동",
            ],
            dong17: [
                "상도동",
                "동작동",
                "사당동",
                "노량진동",
                "상도1동",
                "본동",
                "흑석동",
                "대방동",
                "신대방동",
            ],
            dong18: ["신림동", "봉천동", "남현동"],
            dong19: [
                "원지동",
                "우면동",
                "염곡동",
                "반포동",
                "내곡동",
                "방배동",
                "양재동",
                "신원동",
                "잠원동",
                "서초동",
            ],
            dong20: [
                "논현동",
                "세곡동",
                "자곡동",
                "삼성동",
                "개포동",
                "수서동",
                "신사동",
                "일원동",
                "압구정동",
                "역삼동",
                "도곡동",
                "대치동",
                "율현동",
                "청담동",
            ],
            dong21: [
                "석촌동",
                "장지동",
                "문정동",
                "풍납동",
                "마천동",
                "오금동",
                "신천동",
                "잠실동",
                "거여동",
                "송파동",
                "가락동",
                "삼전동",
                "방이동",
            ],
            dong22: [
                "석촌동",
                "장지동",
                "문정동",
                "풍납동",
                "마천동",
                "오금동",
                "신천동",
                "잠실동",
                "거여동",
                "송파동",
                "가락동",
                "삼전동",
                "방이동",
            ],
        };
    },

    methods: {
        addKakaoMapScript() {
            const script = document.createElement("script");
            /* global kakao */
            script.onload = () => kakao.maps.load(this.initMap);
            script.src =
                "http://dapi.kakao.com/v2/maps/sdk.js?autoload=false&appkey=a28733cc66030bea8246c568ee6595d7";
            document.head.appendChild(script);
        },
        initMap() {
            var container = document.getElementById("map"); //지도를 담을 영역의 DOM 레퍼런스
            var options = {
                //지도를 생성할 때 필요한 기본 옵션
                center: new kakao.maps.LatLng(33.450701, 126.570667), //지도의 중심좌표.
                level: 3, //지도의 레벨(확대, 축소 정도)
            };

            this.$data["map"] = new kakao.maps.Map(container, options); // eslint-disable-line no-unused-vars
        },
        selectDong(s_value) {
            var index = this.gugunoption.findIndex(function (item) {
                return item.value === s_value;
            });
            if (index == -1) {
                return [""];
            } else {
                return this.$data["dong" + index];
            }
        },
    },
};
</script>

<style>
.map {
    width: 100%;
    height: 400px;
}
</style>
